src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Category_ID__c</fullName>
        <formula>CASESAFEID(PricebookEntry.Product2.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fee_Applies__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if an Activity or Program Fee applies</description>
        <inlineHelpText>Indicates if an Activity or Program Fee applies</inlineHelpText>
        <label>Fee Applies</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Occurrences__c</fullName>
        <label>Number of Occurrences</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Payment_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TDT_Support_Provided__c</fullName>
        <label>TDT Support Provided</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_value__c</fullName>
        <formula>Quantity  *  UnitPrice</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Per_Occurrence__c</fullName>
        <label>Units Per Occurrence</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/globalValueSets/Payment_Method.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>NDIA Managed</fullName>
    </customValue>
    <customValue>
        <fullName>Plan Managed</fullName>
    </customValue>
    <customValue>
        <fullName>Self Managed</fullName>
    </customValue>
    <customValue>
        <fullName>Self Funded</fullName>
    </customValue>
    <masterLabel>Payment Method</masterLabel>
</GlobalValueSet>

src/classes/AddProductsModalMetaProc.cls
public class AddProductsModalMetaProc extends vertic_MetadataProcessor {

    /**
     * ==============================================================================================================
     *                                              PROCESS
     * ==============================================================================================================
     */

    public override vertic_Response process(vertic_Request request) {
        this.request = request == null ? new MetadataRequest() : (MetadataRequest) request;

        this.request.fields = new Set<SObjectField>{
            OpportunityLineItem.Payment_Method__c
        };

        super.process(this.request);

        this.init();

        return this.response;
    }


    /**
     * ==============================================================================================================
     *                                             PRIVATE METHODS
     * ==============================================================================================================
     */

    private void init() {
        List<Category__c> categories = [SELECT Id, Name FROM Category__c ORDER BY Name];
        List<vertic_Structs.SelectOption> categoryOptions = new List<vertic_Structs.SelectOption>();
        for (Category__c categoryVar : categories) {
            String value = categoryVar.Name.substringAfter('(').substringBefore(')').trim();
            value = String.isNotBlank(value) ? value : categoryVar.Name;
            categoryOptions.add(new vertic_Structs.SelectOption(categoryVar.Id, value));
        }
        this.response.selectOptions.put('categoryOptions', categoryOptions);
        String recordId = this.request.getString('recordId');
        Opportunity opportunityVar = (Opportunity) vertic_Utils.arrays.firstOrException(
            [
                SELECT
                    Pricebook2Id,
                    Contact__c,
                    Contact__r.MailingState,
                    Contact__r.OtherState
                FROM Opportunity
                WHERE Id = :recordId
            ],
            'There is no Opportunity record with ID: ' + recordId
        );
        this.response.getMapper().mapFromSObject('opportunity', opportunityVar);
        this.response.getMapper().mapFromListSObjects('products', [
            SELECT
                Number_of_Occurrences__c,
                Units_Per_Occurrence__c,
                Quantity,
                ListPrice,
                UnitPrice,
                Payment_Method__c,
                Fee_Applies__c,
                TDT_Support_Provided__c,
                Product2Id,
                Category_ID__c,
                Total_value__c,
                OpportunityId
            FROM OpportunityLineItem
            WHERE OpportunityId = :recordId
        ], new vertic_AutoMapper.BinderQueue(new LineItemBinder()));
    }


    /**
     * ==============================================================================================================
     *                                         STRUCTURES AND OVERRIDES
     * ==============================================================================================================
     */

    // Proposed Live Templates to override Super properties: 
    // vertic_meta_request
    // vertic_meta_response

    private class LineItemBinder implements vertic_AutoMapper.IBinder {

        public LineItemBinder() {}

        public void bind(SObject record, Map<String, Object> dataMap) {
            dataMap.put('prevProduct2Id', record.get('Product2Id'));
        }
    }

}