src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Category_Budget__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Amount__c</fullName>
        <label>Actual Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Category Budgets</relationshipLabel>
        <relationshipName>Category_Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Category Budgets</relationshipLabel>
        <relationshipName>Category_Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Category Budget</label>
    <nameField>
        <displayFormat>CBID-{00000}</displayFormat>
        <label>Category Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Total_value__c</fullName>
        <formula>Quantity  *  UnitPrice</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/CategoryBudgetDomain.cls
global class CategoryBudgetDomain extends fflib_SObjectDomain implements fflib_ISObjectDomain {

    global CategoryBudgetDomain(List<Category_Budget__c> sObjectList) {
        super(sObjectList);
        this.Configuration.disableTriggerCRUDSecurity();
    }

    global class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new CategoryBudgetDomain(sObjectList);
        }
    }
    
    public override void onBeforeInsert() {
        calculateActualAmount(this.getRecords());
    }
    
    public override void onAfterInsert() {}
    
    public override void onBeforeUpdate(Map<Id, SObject> existingRecords) {
        calculateActualAmount(this.getRecords());
    }
    
    public override void onAfterUpdate(Map<Id, SObject> existingRecords) {}

    private static void calculateActualAmount(List<Category_Budget__c> records) {
        Set<Id> categoryIds = vertic_Utils.sObjects.getIdFieldValues(records, Category_Budget__c.Category__c);
        Set<Id> opportunityIds = vertic_Utils.sObjects.getIdFieldValues(records, Category_Budget__c.Opportunity__c);

        Map<Id, Map<Id, List<OpportunityLineItem>>> lineItemsByCategoryIdsByOppIds = new Map<Id, Map<Id, List<OpportunityLineItem>>>();
        for (OpportunityLineItem lineItem : [
            SELECT OpportunityId, Product2.Category__c, Total_value__c
            FROM OpportunityLineItem
            WHERE OpportunityId IN :opportunityIds AND Product2.Category__c IN :categoryIds AND Total_value__c > 0
        ]) {
            if (!lineItemsByCategoryIdsByOppIds.containsKey(lineItem.OpportunityId)) {
                lineItemsByCategoryIdsByOppIds.put(lineItem.OpportunityId, new Map<Id, List<OpportunityLineItem>>());
            }
            if (!lineItemsByCategoryIdsByOppIds.get(lineItem.OpportunityId).containsKey(lineItem.Product2.Category__c)) {
                lineItemsByCategoryIdsByOppIds.get(lineItem.OpportunityId).put(lineItem.Product2.Category__c, new List<OpportunityLineItem>());
            }
            lineItemsByCategoryIdsByOppIds.get(lineItem.OpportunityId).get(lineItem.Product2.Category__c).add(lineItem);
        }

        for (Category_Budget__c categoryBudget : records) {
            if (lineItemsByCategoryIdsByOppIds.containsKey(categoryBudget.Opportunity__c) &&
                lineItemsByCategoryIdsByOppIds.get(categoryBudget.Opportunity__c).containsKey(categoryBudget.Category__c)) {

                List<OpportunityLineItem> lineItems = lineItemsByCategoryIdsByOppIds
                    .get(categoryBudget.Opportunity__c)
                    .get(categoryBudget.Category__c);

                Decimal actualAmount = 0;
                for (OpportunityLineItem lineItem : lineItems) {
                    actualAmount += lineItem.Total_value__c;
                }
                categoryBudget.Actual_Amount__c = actualAmount;
            }
        }
    }

}