src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Category_Budget__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Category Budgets</relationshipLabel>
        <relationshipName>Category_Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category Budget</label>
    <nameField>
        <displayFormat>CBID-{00000}</displayFormat>
        <label>Category Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Category_ID__c</fullName>
        <formula>CASESAFEID(PricebookEntry.Product2.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/OpportunityLineItemDomain.cls
global class OpportunityLineItemDomain extends fflib_SObjectDomain implements fflib_ISObjectDomain {

    global OpportunityLineItemDomain(List<OpportunityLineItem> sObjectList) {
        super(sObjectList);
        this.Configuration.disableTriggerCRUDSecurity();
    }

    global class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new OpportunityLineItemDomain(sObjectList);
        }
    }
    
    public override void onBeforeInsert() {}
    
    public override void onAfterInsert() {
        Set<Id> categoryIds = vertic_Utils.sObjects.getIdFieldValues(this.getRecords(), OpportunityLineItem.Category_ID__c);
        update [SELECT Id FROM Category_Budget__c WHERE Category__c IN :categoryIds];
    }
    
    public override void onBeforeUpdate(Map<Id, SObject> existingRecords) {}
    
    public override void onAfterUpdate(Map<Id, SObject> existingRecords) {
        Set<Id> categoryIds = vertic_Utils.sObjects.getIdFieldValues(this.getRecords(), OpportunityLineItem.Category_ID__c);
        update [SELECT Id FROM Category_Budget__c WHERE Category__c IN :categoryIds];

    }

}