src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Category_Number__c</fullName>
        <label>Category Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NDIS_Portal_Name__c</fullName>
        <description>NDIS portal name</description>
        <label>NDIS Portal Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Australian_States</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NDIS_Portal_Name__c</fullName>
        <formula>Category__r.NDIS_Portal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NDIS Portal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NDIA - ACT</fullName>
                </value>
                <value>
                    <fullName>NDIA - NSW</fullName>
                </value>
                <value>
                    <fullName>NDIA - QLD</fullName>
                </value>
                <value>
                    <fullName>NDIA - VIC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/Australian_States.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACT</fullName>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
    </customValue>
    <customValue>
        <fullName>NT</fullName>
    </customValue>
    <customValue>
        <fullName>QLD</fullName>
    </customValue>
    <customValue>
        <fullName>SA</fullName>
    </customValue>
    <customValue>
        <fullName>TAS</fullName>
    </customValue>
    <customValue>
        <fullName>VIC</fullName>
    </customValue>
    <customValue>
        <fullName>WA</fullName>
    </customValue>
    <customValue>
        <fullName>National</fullName>
    </customValue>
    <description>Reference list of all Australian States</description>
    <masterLabel>Australian States</masterLabel>
</GlobalValueSet>

src/classes/GenerateStatementMetaProcTest.cls
@IsTest
private class GenerateStatementMetaProcTest {
    static testMethod void testBehavior() {
        Contact con = new Contact(LastName = 'test', MailingState = 'VIC', OtherState = 'VIC');
        insert con;

        Category__c category = new Category__c(Name = 'test', NDIS_Portal_Name__c = 'test', Category_Number__c = 1);
        insert category;

        Opportunity opp = new Opportunity(Name = 'test', Contact__c = con.Id, CloseDate = Date.today(), StageName = 'Closed Won');
        insert opp;

        Product2 product2Var = new Product2(Name = 'test', Category__c = category.Id);
        insert product2Var;

        Pricebook2 pricebook2Var = new Pricebook2(Name = 'test', State__c = Pricebook2.State__c.getDescribe().getPicklistValues()[0].value);
        insert pricebook2Var;

        PricebookEntry pricebookEntryVar = new PricebookEntry(Product2Id = product2Var.Id, UnitPrice = 1, Pricebook2Id = Test.getStandardPricebookId(), IsActive = true);
        insert pricebookEntryVar;

        OpportunityLineItem lineItem = new OpportunityLineItem(OpportunityId = opp.Id, Product2Id = product2Var.Id, Quantity = 1, UnitPrice = 1, PricebookEntryId = pricebookEntryVar.Id);
        insert lineItem;

        PageReference pageRef = new PageReference('/');
        pageRef.getParameters().put('id', opp.Id);
        Test.setCurrentPage(pageRef);

        vertic_Response resp = new GenerateStatementMetaProc().process(new vertic_MetadataProcessor.MetadataRequest());

        System.assert(resp.isValid);
        System.assert(resp.has('components'));
    }
}